@extends('layouts.app')
@php($seoImage=$post->image?(str_starts_with($post->image,'demo/')?asset('images/'.$post->image):Storage::url($post->image)):null)
@section('title',$post->meta_title ?: $post->title)
@section('meta_description',$post->meta_description ?: $post->excerpt)
@section('meta_keywords',$post->meta_keywords)
@section('meta_image',$seoImage)
@section('og_type','article')
@section('content')
<section class="article-header"><div class="container"><div class="row justify-content-center"><div class="col-lg-9"><span class="article-category">{{ ucfirst($post->category) }}</span><h1>{{ $post->title }}</h1><div class="article-meta"><span><i class="bi bi-calendar3"></i> {{ optional($post->published_at)->translatedFormat('d F Y') }}</span><span><i class="bi bi-person"></i> {{ $post->author_display_name }}@if($post->author?->unit_name)<small> · {{ $post->author->unit_name }}</small>@endif</span><span><i class="bi bi-eye"></i> {{ number_format($post->views) }} dibaca</span></div></div></div></div></section>
<section class="pb-5"><div class="container"><div class="row justify-content-center"><div class="col-lg-9">@if($post->image)@php($img=str_starts_with($post->image,'demo/')?asset('images/'.$post->image):Storage::url($post->image))<img src="{{ $img }}" class="article-cover" alt="{{ $post->title }}">@endif<div class="article-body">{!! $post->content !!}</div><div class="share-box"><strong>Bagikan:</strong><a target="_blank" href="https://wa.me/?text={{ urlencode($post->title.' '.request()->url()) }}"><i class="bi bi-whatsapp"></i></a><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={{ urlencode(request()->url()) }}"><i class="bi bi-facebook"></i></a><button onclick="navigator.clipboard.writeText(location.href)" title="Salin tautan"><i class="bi bi-link-45deg"></i></button></div></div></div></div></section>
@if($related->isNotEmpty())<section class="section-space bg-soft"><div class="container"><h2 class="section-title mb-4">Konten Terkait</h2><div class="row g-4">@foreach($related as $item)<div class="col-md-6 col-lg-3"><article class="mini-card"><span>{{ optional($item->published_at)->translatedFormat('d M Y') }}</span><h4><a href="{{ route('posts.show',$item) }}">{{ $item->title }}</a></h4></article></div>@endforeach</div></div></section>@endif
@endsection