@extends('admin.layout')
@section('title','Dashboard')
@section('page_title','Dashboard')
@section('page_subtitle',auth()->user()->isAdmin()?'Selamat datang di dashboard portal Madrasah':'Selamat datang di dashboard penulis artikel madrasah')
@section('content')
@if(!auth()->user()->isAdmin())
<div class="row g-4 mb-4">
@foreach([['Artikel Saya',$stats['posts'],'bi-journal-text','admin.posts.index'],['Draft',$stats['drafts'],'bi-file-earmark','admin.posts.index'],['Sudah Terbit',$stats['published'],'bi-check-circle','admin.posts.index']] as $item)
<div class="col-md-4"><a href="{{ route($item[3]) }}" class="stat-card"><span class="stat-icon"><i class="bi {{ $item[2] }}"></i></span><div><strong>{{ $item[1] }}</strong><small>{{ $item[0] }}</small></div><i class="bi bi-arrow-up-right stat-arrow"></i></a></div>
@endforeach
</div>
<div class="alert alert-success"><i class="bi bi-lightbulb me-2"></i>Tulis kegiatan pembelajaran, inovasi guru, prestasi, opini pendidikan, atau praktik baik madrasah. Nama penulis diambil otomatis dari akun SSO.</div>
<div class="admin-card"><div class="card-heading"><div><h3>Artikel Saya</h3><p>Draft dan artikel yang telah diterbitkan</p></div><a href="{{ route('admin.posts.create') }}" class="btn btn-primary btn-sm"><i class="bi bi-plus-lg"></i> Tulis Artikel</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Judul</th><th>Status</th><th>Dibuat</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($latestPosts as $post)<tr><td><strong>{{ Str::limit($post->title,70) }}</strong></td><td><span class="status-dot {{ $post->status==='published'?'published':'draft' }}">{{ ucfirst($post->status) }}</span></td><td>{{ $post->created_at->format('d/m/Y') }}</td><td class="text-end">@if($post->status==='draft')<a href="{{ route('admin.posts.edit',$post) }}" class="btn btn-light btn-sm"><i class="bi bi-pencil"></i></a>@else<a target="_blank" href="{{ route('posts.show',$post) }}" class="btn btn-light btn-sm"><i class="bi bi-eye"></i></a>@endif</td></tr>@empty<tr><td colspan="4" class="text-center py-5 text-secondary">Anda belum menulis artikel.</td></tr>@endforelse</tbody></table></div></div>
@else
<div class="row g-4 mb-4">
@foreach([['Konten',$stats['posts'],'bi-newspaper','admin.posts.index'],['Halaman',$stats['pages'],'bi-file-earmark-text','admin.pages.index'],['GTK',$stats['staff'],'bi-people','admin.staff.index'],['Galeri',$stats['galleries'],'bi-images','admin.galleries.index'],['Infografis',$stats['infographics'],'bi-file-earmark-bar-graph','admin.infographics.index'],['Pesan Baru',$stats['messages'],'bi-envelope','admin.messages.index']] as $item)
<div class="col-6 col-xl"><a href="{{ route($item[3]) }}" class="stat-card"><span class="stat-icon"><i class="bi {{ $item[2] }}"></i></span><div><strong>{{ $item[1] }}</strong><small>{{ $item[0] }}</small></div><i class="bi bi-arrow-up-right stat-arrow"></i></a></div>
@endforeach
</div>
<div class="row g-4"><div class="col-xl-7"><div class="admin-card"><div class="card-heading"><div><h3>Konten Terbaru</h3><p>Berita, artikel, prestasi, dan pengumuman</p></div><a href="{{ route('admin.posts.create') }}" class="btn btn-primary btn-sm"><i class="bi bi-plus-lg"></i> Tambah</a></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Judul</th><th>Penulis</th><th>Status</th><th>Tanggal</th></tr></thead><tbody>@foreach($latestPosts as $post)<tr><td><a href="{{ route('admin.posts.edit',$post) }}" class="fw-semibold text-dark">{{ Str::limit($post->title,48) }}</a><small class="d-block text-secondary">{{ ucfirst($post->category) }}</small></td><td>{{ Str::limit($post->author_display_name,25) }}</td><td><span class="status-dot {{ $post->status==='published'?'published':'draft' }}">{{ ucfirst($post->status) }}</span></td><td>{{ $post->created_at->format('d/m/Y') }}</td></tr>@endforeach</tbody></table></div></div></div><div class="col-xl-5"><div class="admin-card"><div class="card-heading"><div><h3>Pesan Terbaru</h3><p>Pesan dari halaman kontak</p></div><a href="{{ route('admin.messages.index') }}" class="text-link-sm">Lihat semua</a></div><div class="message-list">@forelse($latestMessages as $message)<a href="{{ route('admin.messages.show',$message) }}" class="message-item {{ !$message->read_at?'unread':'' }}"><span class="message-avatar">{{ strtoupper(substr($message->name,0,1)) }}</span><div><strong>{{ $message->name }}</strong><span>{{ $message->subject }}</span><small>{{ $message->created_at->diffForHumans() }}</small></div>@if(!$message->read_at)<i class="unread-dot"></i>@endif</a>@empty<p class="text-secondary">Belum ada pesan.</p>@endforelse</div></div></div></div>
@endif
@endsection
