@extends('admin.layout')
@php($editing=$page->exists)
@section('title',$editing?'Edit Halaman':'Tambah Halaman')
@section('page_title',$editing?'Edit Halaman':'Tambah Halaman')
@section('page_subtitle','Kelola isi halaman profil dan metadata SEO')
@section('page_actions')<a href="{{ route('admin.pages.index') }}" class="btn btn-light"><i class="bi bi-arrow-left"></i> Kembali</a>@endsection
@section('content')
<form method="post" enctype="multipart/form-data" action="{{ $editing?route('admin.pages.update',$page):route('admin.pages.store') }}">@csrf @if($editing)@method('put')@endif
<div class="row g-4"><div class="col-xl-8"><div class="admin-card p-4"><div class="mb-3"><label class="form-label">Judul</label><input name="title" value="{{ old('title',$page->title) }}" class="form-control form-control-lg" required></div><div class="mb-3"><label class="form-label">Slug</label><input name="slug" value="{{ old('slug',$page->slug) }}" class="form-control"></div><div class="mb-3"><label class="form-label">Ringkasan</label><textarea name="excerpt" class="form-control" rows="3">{{ old('excerpt',$page->excerpt) }}</textarea></div><div><label class="form-label">Isi Halaman</label><textarea name="content" class="form-control content-editor" rows="18" required>{{ old('content',$page->content) }}</textarea></div></div><div class="admin-card p-4 mt-4"><h5 class="mb-3"><i class="bi bi-search me-2"></i>SEO Halaman</h5><div class="row g-3"><div class="col-12"><label class="form-label">Meta Title</label><input name="meta_title" maxlength="255" value="{{ old('meta_title',$page->meta_title) }}" class="form-control" placeholder="Kosongkan untuk memakai judul halaman"></div><div class="col-12"><label class="form-label">Meta Description</label><textarea name="meta_description" maxlength="500" rows="3" class="form-control">{{ old('meta_description',$page->meta_description) }}</textarea></div><div class="col-12"><label class="form-label">Meta Keywords</label><input name="meta_keywords" value="{{ old('meta_keywords',$page->meta_keywords) }}" class="form-control" placeholder="kata kunci, dipisahkan, koma"></div></div></div></div><div class="col-xl-4"><div class="admin-card p-4"><label class="form-label">Status</label><select name="status" class="form-select mb-3"><option value="published" @selected(old('status',$page->status?:'published')==='published')>Published</option><option value="draft" @selected(old('status',$page->status)==='draft')>Draft</option></select><label class="form-label">Tanggal Publikasi</label><input type="datetime-local" name="published_at" value="{{ old('published_at',optional($page->published_at)->format('Y-m-d\TH:i')?:now()->format('Y-m-d\TH:i')) }}" class="form-control mb-3"><label class="form-label">Gambar</label>@if($page->image)@php($img=str_starts_with($page->image,'demo/')?asset('images/'.$page->image):Storage::url($page->image))<img src="{{ $img }}" class="image-preview mb-3">@endif<input type="file" name="image" class="form-control" accept="image/*"></div><button class="btn btn-primary btn-lg w-100 mt-4">Simpan Halaman</button></div></div></form>
@endsection
